Blooms & Bakes Boutique/Areas/Admin/Controllers/FlowerController.cs
using Blooms___Bakes_Boutique.Areas.Admin.Models.Flower;
using Blooms___Bakes_Boutique.Areas.Admin.Models.Pastry;
using Blooms___Bakes_Boutique.Core.Contracts.Florist;
using Blooms___Bakes_Boutique.Core.Contracts.Flower;
using Blooms___Bakes_Boutique.Core.Contracts.Pastry;
using Blooms___Bakes_Boutique.Core.Contracts.Patissier;
using Blooms___Bakes_Boutique.Core.Services.Pastry;
using Blooms___Bakes_Boutique.Core.Services.Patissier;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Blooms___Bakes_Boutique.Areas.Admin.Controllers
{
	public class FlowerController : AdminController
	{
		private readonly IFlowerService flowerService;
		private readonly IFloristService floristService;

		public FlowerController(
			IFlowerService _flowerService,
			IFloristService _floristService)
		{
			flowerService = _flowerService;
			floristService = _floristService;
		}
		public async Task<IActionResult> MineFlower()
		{
			var userId = User.Id();
			int agentId = await floristService.GetFloristIdAsync(userId) ?? 0;
			var myFlowers = new MyFlowersViewModel()
			{
				AddedFlowers = await flowerService.AllFlowersByFloristIdAsync(agentId),
				GatheredFlowers = await flowerService.AllFlowersByUserId(userId)
			};

			return View(myFlowers);
		}
	}
}

Blooms & Bakes Boutique/Areas/Admin/Controllers/PastryController.cs
using Blooms___Bakes_Boutique.Areas.Admin.Models.Pastry;
using Blooms___Bakes_Boutique.Core.Contracts.Pastry;
using Blooms___Bakes_Boutique.Core.Contracts.Patissier;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Blooms___Bakes_Boutique.Areas.Admin.Controllers
{
	public class PastryController : AdminController
	{
		private readonly IPastryService pastryService;
		private readonly IPatissierService patissierService;

		public PastryController(
			IPastryService _pastryService,
			IPatissierService _patissierService)
		{
			pastryService = _pastryService;
			patissierService = _patissierService;
		}

		public async Task<IActionResult> MinePastry()
		{
			var userId = User.Id();
			int agentId = await patissierService.GetPatissierIdAsync(userId) ?? 0;
			var myPastries = new MyPastriesViewModel()
			{
				AddedPastries = await pastryService.AllPastriesByPatissierIdAsync(agentId),
				TastedPastries = await pastryService.AllPastriesByUserId(userId)
			};

			return View(myPastries);
		}
	}
}

Blooms & Bakes Boutique/Views/Shared/Components/MainMenuComponent/Default.cshtml
@inject IPatissierService patissierService
@inject IFloristService floristService
<ul class="navbar-nav flex-grow-1">
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Pastry" asp-action="AllPastry">All Pastries</a>
	</li>
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Flower" asp-action="AllFlower">All Flowers</a>
	</li>
	@if (this.User?.Identity?.IsAuthenticated ?? false)
	{
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="" asp-controller="Pastry" asp-action="MinePastry">My Pastries</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="" asp-controller="Flower" asp-action="MineFlower">My Flowers</a>
		</li>
		@if (await patissierService.ExistByIdAsync(User.Id()))
		{
			<li class="nav-item">
				<a class="nav-link text-dark" asp-area="" asp-controller="Pastry" asp-action="AddPastry">Add Pastry</a>
			</li>
		}
		@if (await floristService.ExistByIdAsync(User.Id()))
		{
			<li class="nav-item">
				<a class="nav-link text-dark" asp-area="" asp-controller="Flower" asp-action="AddFlower">Add Flower</a>
			</li>
		}
	}
</ul>